### ISSUE TITLE
npm version doesn't play nicely with webpack

### ISSUE THREAD

**Issue by picitujeromanov** [fingerprintjs/fingerprintjs2#387] opened 2018-10-01 13:01 UTC
I'm trying to use the library with vuejs, but after building (webpacking) something trivial like
`
import Fingerprint2 from 'fingerprintjs2'
console.log(Fingerprint2);
`

you get empty object `{}`

**Comment by GrosSacASac** [comment] 2018-10-01 16:15
Hi,
Could you try  
`import * as Fingerprint2 from 'fingerprintjs2'`

**Comment by picitujeromanov** [comment] 2018-10-03 09:45
That doesn't work either

**Comment by alexhayes** [comment] 2018-10-08 01:58
@picitujeromanov are you using server side rendering? If so this is fixed in #378 but hasn't been released on npm yet.

**Comment by Valve** [comment] 2020-07-09 16:53
this will be fixed in v3, we'll be writing a TS version with a good module/bundler support.

**Comment by Finesse** [comment] 2020-09-07 04:25
I can't reproduce it. If you can, please provide a reproducible example. Here is an example where FingerprintJS works with Webpack: [fpjs-wp.zip](https://github.com/fingerprintjs/fingerprintjs2/files/5181032/fpjs-wp.zip) (unzip it and run `npm i && npx webpack`).

**Closed by Finesse** 2020-09-07 04:25 UTC
Labels: bug, help wanted

**Comment by Valve** [comment] 2020-09-07 16:09
@Finesse please provide open gists or projects on Github as example so that things are more discoverable/linkable in the future from other places.

**Comment by Finesse** [comment] 2020-09-07 23:34
@Valve Actually I didn't make the archive intentionally. I made it for my own needs and thought "why not to attach it here". I think making a repository for each small example is excessive. I can't find a way to create a gist behalf fingerprintjs.

Only 2 files are significant there so I could've just typed the code in the comment. Here is the code (for historical reasons):

```js
// package.json

{
  "name": "fpjs-wp",
  "private": true,
  "scripts": {
    "build": "webpack"
  },
  "dependencies": {
    "fingerprintjs2": "^2.1.2"
  },
  "devDependencies": {
    "webpack": "^4.44.1",
    "webpack-cli": "^3.3.12"
  }
}
```

```js
// src/index.js

import Fingerprint2 from 'fingerprintjs2';

console.log(Fingerprint2);
```

Run `npm i && npm run build` and add `dist/main.js` to your HTML, the proper value will be logged.
