### ISSUE TITLE
Fingerprint2 is undefined when using require JS

### ISSUE THREAD

**Issue by AmirSasson** [fingerprintjs/fingerprintjs2#524] opened 2020-04-20 12:01 UTC
### Scenario

- use the CDN fingerprint js,  in addition add the script tag of require js
like 
```
<script src='https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.js'></script>
```
Fingerprint2 is undefined.
apparently, the condition 
```
 if (typeof window !== 'undefined' && typeof define === 'function' && define.amd) {
        define(definition)
    } 
```
is true,  and `define()` is running, after it runs i have no access to Fingerprint2  object.

can you please tell how can i get access to the **FIngerprint2**  if using `define()`
in addition, why do even use it and not just directly creating the object like in 
```
  context[name] = definition()
```
?

**Comment by pisaq** [comment] 2020-05-20 19:48
Still not working on my side :( I'm using it in Magento Store.

**Comment by AmirSasson** [comment] 2020-05-20 20:12
> Still not working on my side :( I'm using it in Magento Store.

The PR hasnt been accepted yet. Maybe u can ping the repo owner to merge it.

**Comment by pisaq** [comment] 2020-05-20 20:36
> > Still not working on my side :( I'm using it in Magento Store.
> 
> The PR hasnt been accepted yet. Maybe u can ping the repo owner to merge it.

I've took the code from PR, so fix here did not worked for me.

**Comment by Valve** [comment] 2020-05-20 22:28
guys, I'm sorry for such a long delay, I'm so much swamped by work.
Will definitely review all pending PRs, including yours @AmirSasson

**Comment by AmirSasson** [comment] 2020-05-21 05:38
So obviously you have a different problem.
What error/behavior do u have?

**Comment by pisaq** [comment] 2020-05-21 07:49
> So obviously you have a different problem. What error/behavior do u have?
> […](#)

`ReferenceError: Can't find variable: Fingerprint2`

**Comment by pisaq** [comment] 2020-05-21 09:23
@Valve, we believe in you ! ;-)

**Comment by pisaq** [comment] 2020-05-23 10:44
@AmirSasson I've fixed it by doing this 
https://github.com/Valve/fingerprintjs2/issues/320#issuecomment-633024303

**Comment by Valve** [comment] 2020-07-09 16:49
v3 will be implemented in TypeScript with good module support.

**Comment by Finesse** [comment] 2020-09-04 11:43
@AmirSasson @pisaq It looks strange. Could you please share your HTML code or the parts of the code that load and run scripts?

- If you have an HTML like this:
    ```html
    <script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/fingerprintjs2@2.1.2/dist/fingerprint2.min.js"></script>
    ```
    Then you should get a [«Mismatched anonymous define()» error](https://requirejs.org/docs/errors.html#mismatch).
- If you have an HTML like this:
    ```html
    <script src="https://cdn.jsdelivr.net/npm/fingerprintjs2@2.1.2/dist/fingerprint2.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/requirejs@2.3.6/require.min.js"></script>
    ```
    Then the `Fingerprint2` variable should be available in global scope.
- If you don't have a tag like this:
    ```html
    <script src="https://cdn.jsdelivr.net/npm/fingerprintjs2@2.1.2/dist/fingerprint2.min.js"></script>
    ```
    Then this is not a FingerprintJS bug but a proper behavior of the UMD standard (followed by `fingerprint2.js`). To workaround, either:
    - Wrap your `Fingerprint2.get()` calls in `require(['your/path/to/fingerprint2.js'], (Fingerprint2) => Fingerprint2.get())`.
    - Or add a FingerprintJS script tag before the RequireJS script tab like in the code example above.

**Comment by Finesse** [comment] 2020-09-04 12:02
The issue is closed in favor of https://github.com/fingerprintjs/fingerprintjs2/issues/320 because the reason is very similar and the solution will be the same

**Closed by Finesse** 2020-09-04 12:02 UTC
